dns_servers:
  - name: google-doh
    protocol: doh
    url: https://dns.google/dns-query
    verify: true

edns_client_subnets:
  - 180.127.85.0/24
  - 111.193.227.0/24
  - 119.131.222.0/24
  - 112.96.55.0/24
  - 125.78.54.0/24
  - 117.147.86.0/24
  - 222.70.19.0/24


domains:
  - name: sglong.wechat.com
    types: [A]
  - name: sgshort.wechat.com
    types: [A]
  - name: sgminorshort.wechat.com
    types: [A]